### ISSUE TITLE
Resetting/wiping the map

### ISSUE THREAD

**Issue by heymoha** [rterp/GMapsFX#101]
Hi,
we want to add the possibility to reset all data(markers/routes) on the map, without having to close the window, to our program. Yet, i could not find a method to do so, and when we tried to do it by reassigning the variables, it didn't work either.
So, did we miss something, or do you have any idea, how we could do this?
Any help is very much appreciated

**Comment by GeoffCapper** [comment]
You can clear all markers in the latest version, but routes are different. Setting the map to null for the directions renderer is supposed to clear them when using pure JS, and there is the option to do so with the DirectionsRenderer in this library. Whether it has the desired effect is another matter, I haven't looked into the directions side of things. You could store your DirectionsRenderer(s?) (assuming you're using one somehow) and call setMap(null).

The other option would be creating a new GoogleMapView and initialising it, then add it in place of the existing one in your UI. This essentially recreates the WebView and reloads Google Maps within it.

**Comment by heymoha** [comment]
Thanks for the quick answer. For some reason we still have Problems with your second Proposition, so i tried to do it with your first one.
 First, calling setMap(null) on a renderer threw a NullPointerexception, since setMap() uses the variable name of the Parameter. Then i tried to set it to a new GoogleMap, which was nowhere displayed, which worked fine(new routes wouldn't appear anymore), but the old routes did remain on my map.
We will try to get your second guess running, but if anyone could make it possible, that the setMap(null) way works, that would be magnificent.

**Comment by rterp** [comment]
in the 2.11.0 release, clearing directions should work by calling either setMap(null) or the clearDirections() method on the DirectionsRenderer object

[https://github.com/rterp/GMapsFX/wiki/Create-and-Clear-Directions-and--Route](https://github.com/rterp/GMapsFX/wiki/Create-and-Clear-Directions-and--Route)
