### ISSUE TITLE
Using another Geoserver

### ISSUE THREAD

**Issue by akarrayInnovATM** [rterp/GMapsFX#112]
Hi,

I tried your framework, and it's really great.
Currently I'm working on a small UAV project, and I plan to use my own Geoserver.
Can I use my own Geoserver to serve map tile for your framework?
If not, could you please state on which class should I re-implement to be able to use my Geoserver instead of Google map?

Thanks

**Comment by rterp** [comment]
If it uses the same Javascript API as google maps it could work, otherwise a new implementation of the underlying GoogleMap object will need to be created in order to use the other type of Geoserver.
