### ISSUE TITLE
Image Icon does not appear on marker

### ISSUE THREAD

**Issue by RedSt7** [rterp/GMapsFX#123]
Good evening , i can not display an icon on my marker.
I use MarkerImageFactory.createMarkerImage("file:img/t.jpg", "jpg") . It can get the String but it will not put it on marker.. Marker just disappears.. What i am doing wrong?

**Comment by GeoffCapper** [comment]
I've put through a PR that might resolve this issue. For some reason I had round brackets surrounding the data created, which worked in some browsers but not others.

**Comment by RedSt7** [comment]
Yei, you are correct. It works perfectly without the brackets! Thank you very much
