### ISSUE TITLE
Unable to change icon image for marker

### ISSUE THREAD

**Issue by Dlavrov83** [rterp/GMapsFX#126]
Hi, 
I am using the latest version of GMapsFX (2.12.0-3) in my java application.
Everything is working finer except i am not able to change the marker icon to a different image.
I use the next code to do it:
`MarkerOptions markerOptions = new MarkerOptions();
						markerOptions.position(new LatLong(lat, lon))
												.visible(Boolean.TRUE)
												.title(m)
										.icon(MarkerImageFactory.createMarkerImage(System.getProperty("user.dir") + "/flag_blue.png", "png"));
						Marker marker = new Marker(markerOptions); `

When i do that the marker icons still have the same old red marker.
Am i doing something wrong? 
Should i place the image in a different directory?
How do i fix it?

Thank you.

**Comment by GeoffCapper** [comment]
There was a problem with MarkerImageFactory that I've put through a fix on, but it wont have come out in a release yet. I'm guessing this is what will be causing your problem.

Until the next release comes you need to remove the round brackets from the return value of MarkerImageFactory.createMarkerImage. If you can build the library do so with the latest changes I've put up otherwise run a replace to remove ( and ) from the value returned, then set it as the icon.

**Comment by Dlavrov83** [comment]
MarkerOptions markerOptions = new MarkerOptions();
						markerOptions.position(new LatLong(llh[0], llh[1]))
												.visible(Boolean.TRUE)
												.title(m)
												.icon(MarkerImageFactory.createMarkerImageSystem.getProperty("user.dir") + "/flag_blue.png", "png");

like that?

**Comment by Dlavrov83** [comment]
MarkerOptions markerOptions = new MarkerOptions();
						markerOptions.position(new LatLong(llh[0], llh[1]))
												.visible(Boolean.TRUE)
												.title(m)
												.icon(MarkerImageFactory.createMarkerImageSystem.getProperty("user.dir") + "\flag_blue.png", "png");

like that?

**Comment by Dlavrov83** [comment]
ok, i see what you mean. remove it from the output string. will try that.

**Comment by Dlavrov83** [comment]
OK,
I have tried what you proposed
`String iconstr = MarkerImageFactory.createMarkerImage("D://flag_blue.png", "png");`

The return string of the method is `null`, why is that?
Shouldn't that be the path to the image?

**Comment by Dlavrov83** [comment]
Thank you, it works.

**Comment by GeoffCapper** [comment]
Sorry about the confusing explanation, good to read that it works.

**Comment by wdorf** [comment]
Hi

I also get null returned using the following path:
"C:/Users/Warendorf/workspace2/OOS2 Lab/basestation.png"

how is it used correctly?

Or is there a way to display a png/jpg in the map?
