### ISSUE TITLE
Hello people! Please say me how disable white rectangle in right corner of map?

### ISSUE THREAD

**Issue by Medniy2000** [rterp/GMapsFX#127]
[ScreenShoot](https://drive.google.com/file/d/0BwNON3n3eRd6dzlCWFdVbG14LTQ/view?usp=sharing)

**Comment by GeoffCapper** [comment]
I've just merged a commit that adds the fullscreenControl option to MapOptions. You'll need to build from the sources until the next release.

Use it by calling:

    mapOptions.fullscreenControl(false);

Before applying the MapOptions to your map.

**Comment by Medniy2000** [comment]
But i hat not option fullscreenControl in mapOption [ScreeShoot](fullscreenControl(false))
