### ISSUE TITLE
How to save/load route?

### ISSUE THREAD

**Issue by Medniy2000** [rterp/GMapsFX#129]
I want to create route from point A to point B, edit this route exactly where I want to, and save it to the database. Is there any way to do this? I'm about saving/ loading of route. I planned save to database String A point, String B point and string array of waypoints. And I planned: then i will be load theese data I  will create route from A to B and set it waypoints in order to get the exact route previously created(saved in db). But I did not find any setters, opportunities to implement theese. There is some possibility to realize something similar??? Sorry my bad english. Thanks!

**Comment by GeoffCapper** [comment]
DirectionsRequest can take an array of DirectionsWaypoint via the constructor, so this is how you would recreate the route. To save to the database you would process the returned DirectionLegs and store away the start and end locations of each leg. The google maps javascript API for waypoints might offer some useful information, though I'm not sure how much of the functionality has been implemented in the directions component here.

https://developers.google.com/maps/documentation/directions/intro

**Comment by Medniy2000** [comment]
@GeoffCapper, thank you for your help. I was helpful.
