### ISSUE TITLE
Replacing Markers with individual icons

### ISSUE THREAD

**Issue by wdorf** [rterp/GMapsFX#130]
Hi,

I am trying to replace an Icon with the following code:

        String path = "/users/warendorf/workspace2/basestation.png";
        String imgpath = MarkerImageFactory.createMarkerImage(path, "png");
        markerOptions.position( new LatLong(latitude, longitude) )
                    .visible(Boolean.TRUE)
                    .icon(imgpath);

imgpath is null, so nothing happens

Please help

**Comment by wdorf** [comment]
Alternatevily, is there a way to simply place an icon on a map?

**Comment by GeoffCapper** [comment]
I suspect you're trying to access an image on your filesystem, but you're using a classpath style reference. You would need to change it to a file scheme reference "file:///" on Windows, not sure on *nix etc. Maybe just "file:/users/etc..."

The other ways to simply place an icon are to supply your own external html file for the map with your icon images accessible below that, or to recompile the library with the images in the appropriate spot. There is a discussion of each of these in https://github.com/rterp/GMapsFX/issues/39

**Comment by wdorf** [comment]
Hi,

thanks It works this way:
        path = "file:///C:/Users/Warendorf/workspace2/OOS2%20Lab/icons/basestation.png";
        String imgpath = MarkerImageFactory.createMarkerImage(path, "png");
        imgpath = imgpath.replace("(", "");
        imgpath = imgpath.replace(")", "");

Remarks:
- The path must be absolute
- Spaces must be replaced with %20
- The string createMarkerImage returns includes ( and ). These must be removed

Please remove ( and ) in the next version.

**Comment by GeoffCapper** [comment]
Already been fixed for the next version.

**Comment by wdorf** [comment]
A method for a relative path in your file system. Works also in eclipse.

    private String getIcon(String relativeFileLocation) {
        String path = System.getProperty("user.dir") + relativeFileLocation;
        path = path.replace("\\", "/");
        path = "file:///" + path.replace(" ", "%20");
        String imgpath = MarkerImageFactory.createMarkerImage(path, "png");
        imgpath = imgpath.replace("(", "");
        imgpath = imgpath.replace(")", "");
 
        return imgpath;
    }
