### ISSUE TITLE
Adding in the map into a GUI

### ISSUE THREAD

**Issue by EmilySyme** [rterp/GMapsFX#132]
I'm working on a project that we want to add the map into a GUI. The GUI has been coded, and we're just looking to add in the map using this, and I'm just a bit stuck with how to get it visible. We're using intellij, and have imported the GMapsFX library as an external library as a .jar Any tips on how to do this?

**Comment by GeoffCapper** [comment]
MainApp and MainApp2 in package com.lynden.gmapsfx contain working examples of how to use it. You're looking to create an instance of GoogleMapView which you can then add to your GUI.

https://github.com/rterp/GMapsFX/blob/master/GMapsFX/src/main/java/com/lynden/gmapsfx/MainApp.java
