### ISSUE TITLE
Polygons appearing "patchy" when added to map on Windows

### ISSUE THREAD

**Issue by jonesru** [rterp/GMapsFX#179]
Hello,
We are college students working on a project involving several sets of specific locations. When our algorithm is run on MacOS machines, the shapes appear entirely correct on the Google Map. However, when run on a Windows machine, the pushed polygons appear patchy. When the map is zoomed in and out, the shapes seem to be redrawn so the gaps in the lines are shifting in location. As we zoom out farther, the entire data set of shapes changes locations entirely. We have attached images below.
Any help would be much appreciated.
<img width="377" alt="WindowsBug1" src="https://user-images.githubusercontent.com/47308431/54719727-9c54f080-4b2b-11e9-81be-0fc71e674c3a.PNG">
<img width="377" alt="WindowsBugBeforeMove" src="https://user-images.githubusercontent.com/47308431/54719743-a5de5880-4b2b-11e9-8aab-331448b0fec2.PNG">
<img width="380" alt="WindowsBugAfterMove" src="https://user-images.githubusercontent.com/47308431/54719749-ab3ba300-4b2b-11e9-86c5-112485f31f21.PNG">
<img width="377" alt="WindowsBug2" src="https://user-images.githubusercontent.com/47308431/54719761-b55da180-4b2b-11e9-9fad-8887582614d4.PNG">

**Comment by GeoffCapper** [comment]
Hi,

I suspect this will be a problem with JavaFX webview on Windows. All this library does is make use of the standard Google javascript calls, everything else is left to the GoogleMaps javascript API.

**Comment by ppengvan** [comment]
I encounter similar problem after upgrading from Java 8 to 11, and I'm still looking for a solution.

**Comment by jonesru** [comment]
> Hi,
> I suspect this will be a problem with JavaFX webview on Windows. All this library does is make use of the standard Google javascript calls, everything else is left to the GoogleMaps javascript API.

Okay. We will be looking into JavaFX bugs on Windows. Thanks for the response!

**Comment by jonesru** [comment]
> Hi,
> 
> I suspect this will be a problem with JavaFX webview on Windows. All this library does is make use of the standard Google javascript calls, everything else is left to the GoogleMaps javascript API.

We switched from Java 9 down to Java 8, and the polygons are all appearing on the map now! Thanks again!
