### ISSUE TITLE
Undefined Return Values

### ISSUE THREAD

**Issue by GeoffCapper** [rterp/GMapsFX#22]
Hi Rob,

I've put in some sloppy handling of return values throughout that need to be tidied up. In most cases the return value should be the class type of the primitive, so where I'm returning double it should be Double. My question is about booleans... Return false if it's null? Or should we return Boolean which will be more accurate, but introduce the need for extensive null tests throughout the code before we use any boolean value.

I'd suggest Booleans from anything that's going to be in the Javascript library as we wouldn't want to surprise end-users, but for the Google Maps stuff it's often settings, so for example if getEditable returns null, it may as well be false.

What are your thoughts?

**Comment by rterp** [comment]
Closing this issue.
