### ISSUE TITLE
Using other map server

### ISSUE THREAD

**Issue by bromokun** [rterp/GMapsFX#34]
Hi,

I tried your framework, and it's really great.
Currently I'm working on a small GIS project, and I plan to use opensource Geoserver.
I download my country Shapefile from OpenStreetMap ... and deployed it into Geoserver.
My question is: Can I use my own Geoserver to serve map tile for your framework?
If not, could you please state on which class should I re-implement to be able to use my Geoserver instead of Google map?

Thanks

**Comment by rterp** [comment]
Are you still looking to do this?  I'm attempting to prioritize the current open issues on this project.

**Comment by rterp** [comment]
No response
