### ISSUE TITLE
GeoLocation Possibility ?

### ISSUE THREAD

**Issue by minedun6** [rterp/GMapsFX#35]
Hi,
I would like to know if this API has some geolocation services ? and if not could yu make one or show us how to use your package to make one.
By the way, Thx for this great library and the greatness it offers ^^

**Comment by drakator** [comment]
Hello
I am also interested for this

**Comment by rterp** [comment]
What is it you are looking to do exactly?

**Comment by rterp** [comment]
Geolocation API has been implemented.
