### ISSUE TITLE
Updating Marker Options

### ISSUE THREAD

**Issue by roddy-bluedot** [rterp/GMapsFX#36]
A Marker object is instantiated with a MarkerOptions object; once this the Marker is instantiated, the options cannot be accessed. The options contain a visible setting that is unsettable once associated with a Marker which seems incorrect.

**Comment by GeoffCapper** [comment]
I've put a pull request in to make some changes that allow you to call setOptions on the marker and this then obeys the visible state set in the updated MarkerOptions. I can't seem to get it to listen to a change in the MarkerOptions directly. Do you know if it works in a straight JS implementation?

I should also point out that quite a number of methods in the Google Maps API objects have not yet been implemented in the java proxies.

**Comment by GeoffCapper** [comment]
Sorry, didn't mean to close this yet until we're sure the changes do what they claim!

**Comment by roddy-bluedot** [comment]
Hi.  Sorry for the delay; this works like a charm.  Many thanks  :-)

**Comment by GeoffCapper** [comment]
Hi Roddy,

Not sure why you closed all these, they are valid issues, and having 
them there means we would get to addressing them in a useful order for 
people with an interest in using the package?

**Comment by roddy-bluedot** [comment]
Hi,

Apologies, I was just cleaning up after myself; very happy for them to 
remain open.

Roddy
