### ISSUE TITLE
Markers still visible on map after being removed

### ISSUE THREAD

**Issue by roddy-bluedot** [rterp/GMapsFX#37]
Markers that have been removed from the map instance are not removed from the display of the map (they disappear once the map has been zoomed or panned beyond the current window).

As with the previous issue raised, the Marker Options cannot be updated to allow the marker to be made invisible then removed as a workaround.

Is there a way to refresh to map to remove redundant markers?

**Comment by GeoffCapper** [comment]
Hi roddy-bluedot,

Are you using a reference to the GoogleMap object and calling map.removeMarker(marker)? This seemed to work for me when I was testing to implement get/setVisible just now, but it could be a side-effect of other changes.

Cheers,
Geoff

**Comment by roddy-bluedot** [comment]
Hi,

Thanks so much for getting back to me; I am calling map.removeMarker() when processing a UIEventHandler from the (GoogleMap) map object.  I have copied in the code segment below.  On further investigation, when handling the remove within an @FXML action, then the marker is removed from the view but I need to utilise the jsObject from the UIEventHandler.

        map = googleMapView.createMap( mapOptions );

        //  Create the map point processor
        mapPointProcessor = new MapPointProcessing( googleMapView );

        //  Setup the Google map event handlers
        map.addUIEventHandler( UIEventType.click, new UIEventHandler()
        {
            public void handle( JSObject jsObject )
            {
                LatLong latLong = new LatLong( (JSObject) jsObject.getMember( "latLng" ) );

                //  Retrieve the latitude and longitude of the selected location
                double lat = latLong.getLatitude();
                double lon = latLong.getLongitude();

                //  If this is immediate mode, then remove any previous marker
                if ( currentMode == SimulatorModes.immediate )
                {
                    if ( immediateMarker != null )
                    {
                        map.removeMarker( immediateMarker );
                        immediateMarker = null;
                    }
                }

**Comment by drakator** [comment]
I changed the zoom level and then changed again in the previous number.
this refreshed my view and the markers are shown OK after this

**Comment by roddy-bluedot** [comment]
Hi,

Thanks; I previously tried changing it to the same zoom level which didn't work.  The workaround above does cause a refresh.

Thanks again,

**Comment by JuHwon** [comment]
+1 same bug here
