### ISSUE TITLE
Styled Maps

### ISSUE THREAD

**Issue by mirkofetter** [rterp/GMapsFX#40]
Is it possible to use StyledMaps in GMapsFX (http://developers.google.com/maps/documentation/javascript/styling)? If yes, how can one achieve this? Would be nice if there is a simple function to  apply a style  by providing a Style array (like those found here http://snazzymaps.com/explore). Thanks

**Comment by GeoffCapper** [comment]
MapOptions.styleString() slipped through in one of the recent updates. The MainApp.java demo includes it's use.
    options.styleString("[{'featureType':'landscape','stylers':[{'saturation':-100},{'lightness':65},{'visibility':'on'}]},{'featureType':'poi','stylers':[{'saturation':-100},{'lightness':51},{'visibility':'simplified'}]},{'featureType':'road.highway','stylers':[{'saturation':-100},{'visibility':'simplified'}]},{\"featureType\":\"road.arterial\",\"stylers\":[{\"saturation\":-100},{\"lightness\":30},{\"visibility\":\"on\"}]},{\"featureType\":\"road.local\",\"stylers\":[{\"saturation\":-100},{\"lightness\":40},{\"visibility\":\"on\"}]},{\"featureType\":\"transit\",\"stylers\":[{\"saturation\":-100},{\"visibility\":\"simplified\"}]},{\"featureType\":\"administrative.province\",\"stylers\":[{\"visibility\":\"off\"}]},{\"featureType\":\"water\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"on\"},{\"lightness\":-25},{\"saturation\":-100}]},{\"featureType\":\"water\",\"elementType\":\"geometry\",\"stylers\":[{\"hue\":\"#ffff00\"},{\"lightness\":-25},{\"saturation\":-97}]}]");

Gives a greyscale terrain type map for example.
