### ISSUE TITLE
Using Gluon to complile and deploying to an Samsung S5 Android phone.

### ISSUE THREAD

**Issue by leowhss** [rterp/GMapsFX#46]
Within the Gluon compile environment, the desktop version (Windows 10/JDK 8u66) runs very well. However when I deploy and tried running in the S5 Android phone, the JavaFX WebView displays the following: "Web Page not available, net::ERR_UNKNOWN_URL_SCHEME".

It may be that the Android JavaFX Webview treats the embedded maps.html differently from the way the Windows 10 JavaFX Webview component does.

It I instantiate JavaFX Webview and passes in a web URL, both the Windows 10 and Android environment runs identically without any issues.

**Comment by rterp** [comment]
Will look at this as part of the next release.

**Comment by rterp** [comment]
I did an initial test with this using the latest Gluon desktop library and the WebView doesn't load the Google Map, leaving just a gray box where the WebView is on the UI.  Will need to research this  further.
