### ISSUE TITLE
Two questions...

### ISSUE THREAD

**Issue by speakjava** [rterp/GMapsFX#50]
I've just tried out your library and it's perfect for a project I'm working on.  I have two questions, though:

1) For me, all the place names on the maps come up in Spanish.  Is there an easy way to set this to maps.google.co.uk?
2) I don't need the blank scrollpane that is displayed to the left of the map.  Is there a simple way to remove this?

Thanks in advance.

**Comment by genoob** [comment]
Hi, I'm just another user (that also enjoys very much this project), but I think I can help you out with the first question.
Take a look at this line: `<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&language=pt-BR"></script>`  
in this file: https://github.com/rterp/GMapsFX/blob/master/GMapsFX/src/main/resources/html/maps.html

**Comment by speakjava** [comment]
Thanks genoob! That is the answer to my first question.  I changed the language to en, recompiled and now all the place names are in English.

**Comment by speakjava** [comment]
Thanks to the pointer to the HTML file I have solved the second problem I was having.  Removing the <div id="directions"></div> line eliminates the scrollpane I don't want.  Now the API is perfect for my application!  Thanks.

**Comment by rterp** [comment]
Hi @speakjava 
I have created 2 new issues to make these parameters configurable via the JavaFX API, rather than having to modify the underlying html file.
