### ISSUE TITLE
How to get latitude and longitude from mouse click ?

### ISSUE THREAD

**Issue by deepsidhu1313** [rterp/GMapsFX#51]
Hi,

I was experimenting with the code. May i know, how can i get latitude and longitude of the location where i click on map ??

And thanks for the nice project :smile: !!

**Comment by GeoffCapper** [comment]
Hi,

The MainApp file in com.lynden.gmapsfx includes numerous bits of code. 
One of these is the code below that assigns a click handler to the map 
and creates a LatLong object, setting the text of a label as a result:

map.addUIEventHandler(UIEventType.click, (JSObject obj) -> {
     LatLong ll = new LatLong((JSObject) obj.getMember("latLng"));
     //System.out.println("LatLong: lat: " + ll.getLatitude() + " lng: " 
+ ll.getLongitude());
     lblClick.setText(ll.toString());
});

Cheers,
Geoff

**Comment by deepsidhu1313** [comment]
Thanks that solved the problem  !!! :smiley:
