### ISSUE TITLE
Make clear that everyone who is using GMapsFX accepts google license

### ISSUE THREAD

**Issue by aliebelt** [rterp/GMapsFX#52]
Hi,

I really like GMapsFX, but everyone should know that the terms of service of google has to be accepted when using it!
E.g. https://developers.google.com/maps/faq#understanding-terms-of-service

That is a reason why we can not use GMapsFX in our JavaFX application -> our application is not full featured "publicly accessible".

That should be mentioned e.g. in the license section of the GMapsFX README.md.

Best regards

**Comment by rterp** [comment]
Good idea, will do so.

thx,
-Rob
