### ISSUE TITLE
How to get Current Location of User ??

### ISSUE THREAD

**Issue by deepsidhu1313** [rterp/GMapsFX#53]
Is there any way to get current location of the user? Like Google detects from user's browser ??

**Comment by GeoffCapper** [comment]
https://developers.google.com/maps/documentation/javascript/tutorials/geolocation indicates it needs to be done via the geolocation function in the browser platform.

http://stackoverflow.com/questions/37414637/javafx-does-webview-support-geolocation indicates that it's not possible with WebView as it doesn't support that functionality.

You might be able to get the location via the underlying platform. Johan Vos has done some work on this for Android https://www.infoq.com/articles/Building-JavaFX-Android-Apps look down at the second last paragraph.

**Comment by andredornas** [comment]
I used the GeoIP2 and it worked for find my city.

https://github.com/maxmind/GeoIP2-java
