### ISSUE TITLE
Cant get custom icon to load

### ISSUE THREAD

**Issue by TheHell34** [rterp/GMapsFX#59]
Hi,

Im busy with a school project but im trying to get a custom marker icon but it doesn't work.

I placed the image in rescources/html/images/marker-green.png

and i used .icon("images/spotlight-green.png")

can you help me?

**Comment by GeoffCapper** [comment]
Hi TheHell34, sorry about the slow reply. Seems a change to the library stopped these from working. See https://github.com/rterp/GMapsFX/issues/39

**Comment by rterp** [comment]
Duplicate of Issue #39
