### ISSUE TITLE
How to draw PolyLine on streets instead through buildings ??

### ISSUE THREAD

**Issue by deepsidhu1313** [rterp/GMapsFX#60]
Hi,

I have a startpoint and endpoint in LatLong, i want to draw path between those points but i want the path to be on streets/roads instead going through buildings/rivers. Is there any option of Polyline to do that ??
Something similar to snap to roads ?? [https://developers.google.com/maps/documentation/roads/snap#request](snap to road)

**Comment by rterp** [comment]
I don’t think this is possible to do with a Polyline, you will have to use the Directions API in order to do something like this.

**Comment by deepsidhu1313** [comment]
@rterp thanks !! do you have any sample code for that ??

**Comment by rterp** [comment]
Yes,

there is an example app which is using the directions API at:

https://github.com/rterp/GMapsFX/blob/master/GMapsFX/src/main/java/com/lynden/gmapsfx/MainApp.java?



________________________________
