### ISSUE TITLE
Search function using textfields or searchbox?

### ISSUE THREAD

**Issue by vjsamonte** [rterp/GMapsFX#61]
Hi, 

just wanted to know if i could have a searchbox in the map to search places. how do i do that?

and thanks for this gmapsfx, it really helps a lot.

**Comment by rterp** [comment]
What are you looking to do exactly with the search?  Are you looking to enter an address, and then have the map center at that location?

**Comment by vjsamonte** [comment]
yes, indeed. :D

sorry for the late reply.

**Comment by GeoffCapper** [comment]
I use the following function to find a string address. Create a TextField somewhere in your UI to collect the data from the user, then pass the result to a function like this. The variable "map" is the object returned from the call to `GoogleMapView.createMap(options);` Obviously a real program would need a bit better error checking...
```java
public void findAddress(String address) {
    GeocodingService gs = new GeocodingService();
    gs.geocode(address, new GeocodingServiceCallback() {
        @Override
        public void geocodedResultsReceived(GeocodingResult[] grs, GeocoderStatus gs) {
            if (GeocoderStatus.OK.equals(gs)) {
                if (grs.length > 0) {
                    GeocodingResult g = grs[0];
                    LatLongBounds llb = g.getGeometry().getBounds();
                        if (llb != null) {
                            System.out.println("Map Bounds For Location: " + llb);
                            map.fitBounds(llb);
                        }
                    }
                }
            }
    });
}
```
You could replace the use of getBounds() with getLocation() then call setCenter() on the GoogleMap object:
```java
LatLong ctr = g.getGeometry().getLocation();
if (ctr != null) {
    map.setCenter(ctr);
}
```
