### ISSUE TITLE
Basic Map resoucres

### ISSUE THREAD

**Issue by RomGutman** [rterp/GMapsFX#62]
Hi,

Is there a way (by code) to change the maps.html basic layout to 100% of map (instead of 75% map and 25% directions)?

Thx!

**Comment by rterp** [comment]
@RomGutman I'm trying to find a way to do this with javascript, but unfortunately everything that I have attempted to add to the map.html page is not supressinging the directions <div>.  The current workaround is to download the source and manually remove the div.  In the next release of GMaps I'll take out the div if I can't find a way to programatically remove it at runtime.
