### ISSUE TITLE
fitBounds() not implemented in maven-repository?

### ISSUE THREAD

**Issue by klemensh** [rterp/GMapsFX#66]
Hello @rterp,
I am unable to set the bounds (fitBounds) of the Gmap. When I pull your Git, there is no problem with that, but the function is not available in the maven-dependency. Is there a way so solve this?
Regards,
klemensh

**Comment by rterp** [comment]
What version of the dependency are you using?


________________________________

**Comment by klemensh** [comment]
1.1.1

**Comment by rterp** [comment]
The latest version in the Bintray and JCenter maven repos is 2.0.6

**Comment by klemensh** [comment]
When I use v 2.0.6 (I already tried that before) it says, that the dependency could not be found
In my pom.xml I use it just like that: 
        <dependency>
            <groupId>com.lynden</groupId>
            <artifactId>GMapsFX</artifactId>
            <version>2.0.6</version>
            <type>pom</type>
        </dependency>

is there anything wrong with it?

**Comment by rterp** [comment]
Try adding the jcenter maven repo to your settings.xml file.

                  <repository>
                    <name>jcenter</name>
                    <id>2</id>
                    <url>http://jcenter.bintray.com/</url>
                </repository>

**Comment by klemensh** [comment]
Aaand there we go! I worked with maven-repos only until now! I appreciate your support very much, thank you!

**Comment by rterp** [comment]
No problem…I’ll create a new issue in github to investigate why the releases aren’t getting pushed over to maven central.

**Comment by rterp** [comment]
OK, the latest version (2.0.8) has now been synced up with Maven central, so you shouldn't need to use the bintray repo if you don't want to.
