### ISSUE TITLE
Does it support Earth view mode?

### ISSUE THREAD

**Issue by msufred** [rterp/GMapsFX#73]
Hi. As far as the examples I have seen, the maps generated are all in the default map view. Does the api supports the Earth view mode? I mean, with the actual image of the terrains if you know what I mean. Thank you.

**Comment by GeoffCapper** [comment]
You can supply a com.lynden.gmapsfx.javascript.object.MapTypeIdEnum to the MapOptions.mapType()

It comes in TERRAIN, ROADMAP, SATELLITE and HYBRID flavours. You can also supply a style string to the MapOptions.styleString() to take it even further.

If you grab the source the MainApp.java sample in the top package shows examples of usage within a ComboBox etc.
