### ISSUE TITLE
Add onClick event from Map to Java

### ISSUE THREAD

**Issue by FueledByChai** [rterp/GMapsFX#8]
Add the ability to fire an onClick event from the GoogleMapView back to Java.
https://developers.google.com/maps/documentation/javascript/examples/event-simple

**Comment by Zawartek** [comment]
Hello,

Maybe i am wrong, but i don't succeed to do it with a marker.
I want to do something when the user click on a marker (open another stage but it doesn't work ...).

thanks in advance,
Zawartek
