### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by dragoBerto** [rterp/GMapsFX#82]
I'm a novice programmer and I want to use GMapsFX for a project in Eclipse.
I don't understand how to use this API, can someone write some steps to setup a new project?
I know it is probably very simple but I would be gratefull for an explanation.

Thanks,
dragoBerto

**Comment by GeoffCapper** [comment]
MainApp.java contains what is basically a sample project to get started with. I have no idea how Eclipse works, but you should be able to add the jar file to a new project and get started using the examples in there.
https://github.com/rterp/GMapsFX/blob/master/GMapsFX/src/main/java/com/lynden/gmapsfx/MainApp.java

**Comment by dragoBerto** [comment]
Ok but there's no .jar file to download for 2.0.9 release, where can I find it? 
If I install the .jar file with Maven will I be able to launch the MainApp?

Thanks for your time,
dragoBerto
