### ISSUE TITLE
Action listener on marker

### ISSUE THREAD

**Issue by Zawartek** [rterp/GMapsFX#83]
Hello,

I want to do something when the user click on a marker (open another stage but it doesn't work ...).

Maybe i am wrong, but i try to use the same structure that : `map.addUIEventHandler()` but on a marker.

` marker2.addUIEventHandler(UIEventType.click, (JSObject obj) -> {
                    LatLong ll = new LatLong((JSObject) obj.getMember("latLng"));
                    System.out.println("LatLong: lat: " + ll.getLatitude() + " lng: " + ll.getLongitude());
                });`

I think i have created all methods needed in the class Marker.java but that still doesn't work.

thanks in advance for your help,
Zawartek

**Comment by GeoffCapper** [comment]
Try `map.addUIEventHandler(marker2, UIEventType.click, (JSObject obj) -> { etc });` The call needs to be made on the map, using the marker as the first parameter.

**Comment by Zawartek** [comment]
Thanks you it's work.
Have a nice day.
