### ISSUE TITLE
Add a JDBC Driver

### ISSUE THREAD

**Issue by Zawartek** [rterp/GMapsFX#90]
Hello,

I want to add a MySQL database in my application and for that i need to add MySQL JDBC Driver but i have tried many things to configure it but when i compile it Netbeans don't suceed to install the driver.

thanks in advance for your help,
Zawartek

**Comment by Zawartek** [comment]
The message from Netbeans when i tried to compile my project :

Downloading: http://jcenter.bintray.com/mysql/mysql-connector-java/5.1.40/mysql-connector-java-5.1.40.jar
janv. 06, 2017 3:58:25 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute

INFOS: I/O exception (java.net.SocketException) caught when processing request to {}->http://proxy:8080->http://jcenter.bintray.com:80: Malformed reply from SOCKS server

**Comment by GeoffCapper** [comment]
Hi Zwarktek,

This error is not related to GMapsFX
