### ISSUE TITLE
Problem with DirectionsRequest, when i want to use waypoints

### ISSUE THREAD

**Issue by heymoha** [rterp/GMapsFX#91]
Hi,
my usual directionsrequests work just fine, but when i try to use the waypoints[] array, my request doesnt return 'OK' as Status and consequently there is no route shown on the map.

My console shows the following:
REQUEST {origin: '50.04556527,9.77508545',destination: '50.05521005,9.78658676',travelMode: google.maps.TravelMode.DRIVING,optimizeWaypoints: true,waypoints: [DirectionsWaypoint26,]}
Directions direct call: DirectionsService27.route(DirectionsRequest28, function(results, status) {
if(status === 'OK'){
DirectionsRenderer29.setDirections(results);
document.DirectionsService27.processResponse(results, status);
}});

If anyone could help me with this, or if anyone ahd any idea, why it doesn't work, i would very much appreciate it, if you helped me.
Thanks :)

**Comment by kacharif** [comment]
Hi,
I have a same problem with  DirectionsRequests, when i put if you have any idea or you can help me 
Thanks. :)

**Comment by heymoha** [comment]
The Problem is, that for some reason the given method by the package only works, if you use your starting point and destination as Strings, and not in the LatLong format.
I did it like this(I used LatLng instead of LatLong, due to other parts of our project):
public void createComplexRoute(LatLng _origin, LatLng _target, TravelModes _tm,DirectionsWaypoint[] waypoints){
String origin = _origin.toString();
String target = _target.toString();
DirectionsService directionsService = new DirectionsService();
DirectionsRequest request = new DirectionsRequest(origin, target, _tm,waypoints);
request.setOpt(false);
DirectionsRenderer renderer = new DirectionsRenderer(true, map, gmp.getDirec());
directionsService.getRoute(request, this, renderer);
}

I hope this could help you :)
Feel free to message again, if it doesn't work
