### ISSUE TITLE
Delete all Markers on the map

### ISSUE THREAD

**Issue by blackbirdsr71br** [rterp/GMapsFX#92]
Goodnight.

This is an excellent job.

I query a database, with the latitude and loingitud I created the Markers, but, How can I delete all the Markers on the map, so I can make a new query of my database and put the new Markers.

Thank you so much

**Comment by heymoha** [comment]
I made a list, containing all the markers I created. To remove them all, I simply iterated over the list. I don't know, if there are any better solutions, but this should work in any case.

**Comment by rterp** [comment]
I don't believe there is currently a method to easily do this other than what @heymoha  described, but I've flagged this as an enhancement.

**Comment by GeoffCapper** [comment]
Google itself recommends keeping them in an array, iterating that and setting 'map' to null on each, per: https://developers.google.com/maps/documentation/javascript/examples/marker-remove

It would be possible to do that behind the scenes in the addMarker method of the GoogleMap object, and supply a method to clear them all.

**Comment by GeoffCapper** [comment]
The suggestions I've seen offer two options, one to remove the markers but keep them in the collection, the other to remove them and clear the collection. Perhaps just removing them all, and if the end-user wants to keep them in a collection they should be responsible for that? A map.addMarkers(List<>) would be useful in that case too.

**Comment by GeoffCapper** [comment]
Sample for test and use of bulk marker management below using changes in commit #97. Further enhancement might be needed to deal with adding events to the bulk markers, as they can't be added when the marker isn't associated with the map (I don't think...) End-user can iterate their own collection after addition and add listeners in the meantime.

    public class SampleApp extends Application implements MapComponentInitializedListener {
        
        protected GoogleMapView mapComponent;
        protected GoogleMap map;
        
        private List<Marker> localMarkers;
        
        @Override
        public void start(Stage stage) {
            
            mapComponent = new GoogleMapView(Locale.getDefault().getLanguage(), null);
            mapComponent.addMapInializedListener(this);
                    
            BorderPane bp = new BorderPane();
            ToolBar tb = new ToolBar();
            
            Button bClear = new Button("Clear Markers");
            bClear.setOnAction(a -> clearMarkers());
            
            Button bPlace = new Button("Place Markers");
            bPlace.setOnAction(a -> placeMarkers());
            
            Button bRS = new Button("Remove Some Markers");
            bRS.setOnAction(a -> removeSomeMarkers());
            
            tb.getItems().addAll(bClear, bPlace, bRS);
            
            bp.setTop(tb);
            
            bp.setCenter(mapComponent);
    
            Scene scene = new Scene(bp, 700, 700);
            stage.setScene(scene);
            stage.show();
            
        }
    
        @Override
        public void mapInitialized() {
            
            LatLong centre = new LatLong(-43.238968, 146.23352);
            
            MapOptions options = new MapOptions();
            options.center(centre)
                    .zoom(6)
                    .overviewMapControl(false)
                    .panControl(false)
                    .rotateControl(false)
                    .scaleControl(false)
                    .streetViewControl(false)
                    .zoomControl(false)
                    .mapType(MapTypeIdEnum.TERRAIN);
            
            map = mapComponent.createMap(options, false);
            
            createLocalMarkers();
            
            map.addMarkers(localMarkers);
            
        }
        
        private void clearMarkers() {
            map.clearMarkers();
        }
        
        private void placeMarkers() {
            map.addMarkers(localMarkers);
        }
        
        private void removeSomeMarkers() {
            
            Collection<Marker> sm = localMarkers.subList(0, 4);
            map.removeMarkers(sm);
            
        }
        
        private void createLocalMarkers() {
            
            localMarkers = new ArrayList<>();
            double lat = -43.238968;
            double lng = 141.23352;
            
            MarkerOptions mo = null;
            LatLong ll = null;
            
            for (int i = 0; i < 10; i++) {
                
                lng = lng + 1;
                
                mo = new MarkerOptions();
                ll = new LatLong(lat, lng);
                mo.position(ll)
                        .title("A Marker (" + i + ")")
                        .visible(true);
                
                localMarkers.add(new Marker(mo));
                
            }
        }
    }

**Comment by blackbirdsr71br** [comment]
Many thanks for the modification to the library, it works excellent.
But now I have the problem to add an InfoWindow to each Marker in bulk process.
Please help me ,
Thank you so much

**Comment by GeoffCapper** [comment]
As noted above you'll need to iterate your collection of Markers after adding them to add the listeners, at least for now. Not sure how we could deal with adding the listeners during the bulk process, it's something we'll have to brainstorm over!

**Comment by GeoffCapper** [comment]
@rterp @blackbirdsr71br 
I've just put through a pull request that includes an addMarkers method that will take a Callback that can be used to create event handlers on each Marker. Rob, I haven't merged this as you might not want to risk it in the new release, and it might need a bit more consideration and refinement, depending on how it serves in the real world.

Sample usage is as follows, replacing/inserting into yesterdays example. I've used anonymous classes rather than lambdas to make is clear what's happening.

    public void mapInitialized() {
        ... code as above ...
        map.addMarkers(localMarkers, UIEventType.click, new Callback<Marker, UIEventHandler>() {
            @Override
            public UIEventHandler call(Marker param) {
                return new UIEventHandler() {
                    @Override
                    public void handle(JSObject jso) {
                        displayInfoWindow(new LatLong((JSObject) jso.getMember("latLng")), param);
                    }
                };
            }
        });
    }
    
    private void displayInfoWindow(LatLong loc, Marker m) {
        InfoWindowOptions infoOptions = new InfoWindowOptions();
        infoOptions.content("<h2>Info Window</h2><p>Describing marker: " + m.getTitle() + " at location: " + loc.toString() + "</p>");
        InfoWindow window = new InfoWindow(infoOptions);
        window.open(map, m);
    }

**Comment by blackbirdsr71br** [comment]
good morning

It is an excellent library, and the answers are very good, thank you very much for your help, I downloaded version 2.10.0 and it works great, this question is closed.

Thank you very much.
