### ISSUE TITLE
How can I delete a route?

### ISSUE THREAD

**Issue by heymoha** [rterp/GMapsFX#93]
Hi, 
is there any way to delete a route, once i created it?
If there is, how do I do it?
Thanks for your help

**Comment by rterp** [comment]
There will be a clearDirections() method on the DirectionsRenderer class in the 2.11.0 release.

[https://github.com/rterp/GMapsFX/wiki/Create-and-Clear-Directions-and--Route](https://github.com/rterp/GMapsFX/wiki/Create-and-Clear-Directions-and--Route)
