### ISSUE TITLE
MarkerOptions icon not showing image

### ISSUE THREAD

**Issue by leganas** [rterp/GMapsFX#94]
if you use the structure

```
markerOptions.position(markerLatLong)
     .icon(MarkerImageFactory.createMarkerImage("image/filename.png", "png"))
     . . .

```
then absolute path com.linden.gmapsfx.util.image/filename.png

the solution described https://github.com/rterp/GMapsFX/issues/39  does not work
gmapsfx version 2.0.9 from Maven,
`MarkerImageFactory.createMarkerImageFromFile`
method does not contain :(

**Comment by rterp** [comment]
@leganas so does your image need to get loaded from:

d:\MyProject\ServerJavaFX\src\image\Arrow_3.png
or
from the classpath at:
/image/Arrow_3.png

**Comment by GeoffCapper** [comment]
Hi Leganas & Rob,

I added support for the file scheme in December. The 2.0.9 release was August so it wont include the support for file:/// yet. It will have to be in 2.0.10

**Comment by rterp** [comment]
I'll get a release build done tomorrow for the changes.

**Comment by blackbirdsr71br** [comment]
This function for me


mrkoption.position(ptmarca)
                     .title("Luminaria")
                     .icon(MarkerImageFactory.createMarkerImage("file:/cfe/lumiconn.png", "png"));
