### ISSUE TITLE
Garbled text on OSX

### ISSUE THREAD

**Issue by rterp** [rterp/GMapsFX#95]
Text on the sample application is initially loading correctly, but then turns garbled within a second.

The issue has been reported on OSX,  JREs 1.8.0_66 and _121

![map](https://cloud.githubusercontent.com/assets/7119529/22956235/ac424a98-f2d5-11e6-9b52-7bba011540db.jpg)

**Comment by rterp** [comment]
This appears to be an issue with JavaFX WebView and Google Maps on OSX (works fine on linux).  Will submit a bug report to the JavaFX team.

**Comment by skaflux** [comment]
Tested on Windows and it works fine as well. So it looks like it is only a problem on OSX.

**Comment by DonavanMartin** [comment]
I have same problem on OS X.

**Comment by rterp** [comment]
I've submitted a bug report to Oracle with an example test case that demonstrates the issue with the WebView.  I'll update this issue with the Oracle ticket number once its approved.

**Comment by rterp** [comment]
Oracle has acknowledged that this is a known issue and the fix for it is in Java 9.

[http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8088205](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8088205)

**Comment by rterp** [comment]
I have a workaround for the issue which should fix the issue in the next release of GMapsFX 2.12.0
