### ISSUE TITLE
How can I catch the Lat/Long of clicks

### ISSUE THREAD

**Issue by rterp** [rterp/GMapsFX#96]
Question received from user:

Can you explain how I can add Event Handler on mouse clicks ? and How can I catch the Lat/Long of clicks ?

**Comment by GeoffCapper** [comment]
Hi Rob,

MainApp.java contains the following as a usage sample:

    map.addUIEventHandler(UIEventType.click, (JSObject obj) -> {
        LatLong ll = new LatLong((JSObject) obj.getMember("latLng"));
        //System.out.println("LatLong: lat: " + ll.getLatitude() + " lng: " + ll.getLongitude());
        lblClick.setText(ll.toString());
    });

**Comment by rterp** [comment]
Ah Excellent.  I'm going to start to document answers to the questions in the issue tracker on my blog as well as put them into the wiki.

**Comment by rterp** [comment]
Wiki updated, example app created, blog post created.
